title: School shtuff		
email: 4410@schravenlant.nl		
lang: nl
description: >-		
  Dit is een website die ik even snel heb gemaakt voor mijn school stuff. Ik plaats hier mijn samenvattingen en leerplanningen voor de toetsweek in de hoop dat iemand anders er ook nog iets aan heeft.		
baseurl: "/"		
url: "https://school.geheimesite.nl"		
github_username: RobinBoers
