source "https://rubygems.org"

gem "jekyll"
gem "jekyll-default-layout"
gem "jekyll-readme-index"
gem "jekyll-titles-from-headings"
gem "jekyll-commonmark-ghpages"
gem "jekyll-relative-links"
gem "jekyll-optional-front-matter"
gem "jekyll-sitemap"